name: Trigger Create Release

on:
  create

jobs:
  update-version:
    version-0.0.10-create-release
    if: startsWith(github.ref_name, 'version-') && endsWith(github.ref_name, '-create-release')
    name: Update Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install typer==0.4.0

      - name: Test Environment
        run: |
          VERSION='${{ github.ref_name }}'
          VERSION=${VERSION//-create-release/}

          # setup git
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # switch to master
          git checkout master

          # update version
          python scripts/update_version.py $VERSION
          git commit -am "Update version to $VERSION"

          # create tag
          git tag $VERSION

          # push to master
          git push origin master --tags

          # delete branch
          git push -d origin ${{ github.ref_name }}
        