name: Trigger Create Release

on:
  release:
    types: [draft]

  pull_request:

jobs:
  release:
    if: endsWith(github.event.release.name, '[create-release]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Test Environment
        run: |
          python -c "import os; print(os.environ['github.event.release.name'])"